// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package files

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Video-0]
	_ = x[Audio-1]
	_ = x[Image-2]
	_ = x[Document-3]
	_ = x[Archive-4]
	_ = x[Font-5]
	_ = x[Unknown-6]
}

const _Type_name = "videoaudioimagedocumentarchivefontunknown"

var _Type_index = [...]uint8{0, 5, 10, 15, 23, 30, 34, 41}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
