// Code generated by "stringer -type=Unit -linecomment"; DO NOT EDIT.

package files

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[B-0]
	_ = x[Kb-1]
	_ = x[Mb-2]
	_ = x[Gb-3]
	_ = x[Tb-4]
	_ = x[Pb-5]
	_ = x[Eb-6]
}

const _Unit_name = "BKBMBGBTBPBEB"

var _Unit_index = [...]uint8{0, 1, 3, 5, 7, 9, 11, 13}

func (i Unit) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Unit_index)-1 {
		return "Unit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Unit_name[_Unit_index[idx]:_Unit_index[idx+1]]
}
